// // import { test, expect } from '@playwright/test';

// // test('test', async ({ page }) => {
// //   await page.goto('https://staging.roadreadywheels.com/');
// //   await page.getByPlaceholder('Enter password').click();
// //   await page.getByPlaceholder('Enter password').fill('roadready');
// //   await page.getByPlaceholder('Enter password').press('Enter');
// //   await page.getByRole('button', { name: 'SUBMIT', exact: true }).click();
// //   await page.locator('#make-button').getByText('-Select Make-').click();
// //   await page.getByRole('option', { name: 'BMW' }).click();
// //   await page.locator('#model-button').getByText('-Select Model-').click();
// //   await page.getByRole('option', { name: '320i' }).click();
// //   await page.click("[id='filter-search-button']");
// //   await page.getByText('5', { exact: true }).click();
// //   await page.getByText('OEM Replacement Wheel').click();
// //   await page.locator('.font15 > span').first().click();
// //   await page.getByPlaceholder('Enter Zip Code').click();
// //   await page.getByPlaceholder('Enter Zip Code').fill('30012');
// //   await page.getByRole('button', { name: 'Continue' }).click();
// //   await page.getByRole('link', { name: '2012-2018 17x7.5 BMW 320i Aluminum Wheel / Rim', exact: true }).first().click();
// //   await page.locator('#inside-product-cart-form div').filter({ hasText: 'Quantity:1 2 3 4 5 6 7 8 9 10' }).nth(2).click();
// //   await page.locator('#inside-product-cart-form div').filter({ hasText: 'Quantity:1 2 3 4 5 6 7 8 9 10' }).nth(2).click();
// //   await page.locator('#inside-product-cart-form div').filter({ hasText: 'Quantity:1 2 3 4 5 6 7 8 9 10' }).nth(2).click();
// //   await page.locator('#inside-product-cart-form div').filter({ hasText: 'Quantity:1 2 3 4 5 6 7 8 9 10' }).nth(2).click();
// //   await page.locator('#inside-product-cart-form div').filter({ hasText: 'Quantity:1 2 3 4 5 6 7 8 9 10' }).nth(2).click();
// //   await page.goto('https://staging.roadreadywheels.com/products/12-18-17x7-5-bmw-320i-aluminum-wheel-rim');
// //   await page.getByRole('button', { name: ' Add To Cart' }).click();
// //   await page.waitForTimeout(2000);
// //   await page.getByRole('button', { name: ' Complete Checkout' }).click();
// //   await page.getByRole('button', { name: 'Continue' }).click();
// //   await page.getByPlaceholder('Email').click();
// //   await page.getByPlaceholder('Email').fill('rg@g.com');
// //   await page.getByPlaceholder('Email').press('Tab');
// //   await page.getByRole('textbox', { name: 'First Name' }).fill('rishabh');
// //   await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
// //   await page.getByRole('textbox', { name: 'Last Name' }).fill('gangwar');
// //   await page.getByRole('textbox', { name: 'Street Address 1' }).click();
// //   await page.getByRole('textbox', { name: 'Street Address 1' }).fill('dwarka');
// //   await page.getByRole('textbox', { name: 'Street Address 1' }).press('Tab');
// //   await page.getByRole('textbox', { name: 'Street Address 2' }).fill('delhi');
// //   await page.getByRole('textbox', { name: 'Street Address 2' }).press('Tab');
// //   await page.getByRole('textbox', { name: 'City' }).fill('delhi');
// //   await page.getByRole('textbox', { name: 'City' }).press('Tab');
// //   await page.locator('#order_ship_address_attributes_state_id').selectOption('3529');
// //   await page.getByRole('textbox', { name: 'Zipcode' }).click();
// //   await page.getByRole('textbox', { name: 'Zipcode' }).fill('30012');
// //   await page.locator('#order_ship_address_attributes_state_id').selectOption('3535');
// //   await page.getByRole('textbox', { name: 'Phone' }).click();
// //   await page.getByRole('textbox', { name: 'Phone' }).fill('999999999');
// //   await page.getByRole('button', { name: 'Continue' }).nth(1).click();
// //   await page.waitForTimeout(2000);
// //   await page.locator('#test-continue').click();
// //   await page.getByText('Credit Card').click();
// //   await page.getByPlaceholder('Card Number').click();
// //   await page.getByPlaceholder('Card Number').fill('4111 1111 1111 1111');
// //   await page.getByPlaceholder('Security Code').click();
// //   await page.getByPlaceholder('Security Code').fill('123');
// //   await page.locator('#expiry_month').selectOption('7');
// //   await page.locator('#expiry_year').selectOption('2032');
// //   await page.waitForTimeout(1000);
// //   await page.getByRole('button', { name: 'Place Your Order' }).click();
// //   await page.waitForTimeout(1000);
// // });
// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   test.slow();
//   await page.goto('https://staging.roadreadywheels.com/');
//   await page.getByPlaceholder('Enter password').click();
//   await page.getByPlaceholder('Enter password').fill('roadready');
//   await page.getByPlaceholder('Enter password').press('Enter');
//   await page.getByRole('button', { name: 'SUBMIT', exact: true }).click();
//   await page.locator('#make-button').getByText('-Select Make-').click();
//   await page.getByRole('option', { name: 'BMW' }).click();
//   await page.locator('#model-button').getByText('-Select Model-').click();
//   await page.getByRole('option', { name: '320i' }).click();
//   await page.getByRole('button', { name: 'SEARCH' }).click();
//   await page.getByText('5', { exact: true }).click();
//   await page.waitForTimeout(1000);
//   await page.getByRole('link', { name: 'Best Match 2001-2005 16x7 BMW' }).first().click();
//   await page.getByRole('button', { name: ' Add To Cart' }).click();
//   await page.waitForTimeout(1000);
//   await page.getByRole('button', { name: ' Complete Checkout' }).click();
//   await page.getByRole('button', { name: 'Continue' }).click();
//   await page.waitForTimeout(2000);
//   await page.getByPlaceholder('Email').click();
//   await page.getByPlaceholder('Email').fill('rg@g.com');
//   await page.getByPlaceholder('Email').press('Tab');
//   await page.getByRole('textbox', { name: 'First Name' }).fill('rishabh');
//   await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
//   await page.getByRole('textbox', { name: 'Last Name' }).fill('gangwar');
//   await page.getByRole('textbox', { name: 'Street Address 1' }).click();
//   await page.getByRole('textbox', { name: 'Street Address 1' }).fill('dwarka');
//   await page.getByRole('textbox', { name: 'Street Address 1' }).press('Tab');
//   await page.getByRole('textbox', { name: 'Street Address 2' }).fill('delhi');
//   await page.getByRole('textbox', { name: 'Street Address 2' }).press('Tab');
//   await page.getByRole('textbox', { name: 'City' }).fill('delhi');
//   await page.getByRole('textbox', { name: 'City' }).press('Tab');
//   await page.locator('#order_ship_address_attributes_state_id').selectOption('3529');
//   await page.getByRole('textbox', { name: 'Zipcode' }).click();
//   await page.getByRole('textbox', { name: 'Zipcode' }).fill('30012');
//   await page.locator('#order_ship_address_attributes_state_id').selectOption('3535');
//   await page.getByRole('textbox', { name: 'Phone' }).click();
//   await page.getByRole('textbox', { name: 'Phone' }).fill('999999999');

//   await page.getByRole('button', { name: 'Continue' }).nth(1).click();
//   await page.waitForTimeout(2000);
//   await page.goto('https://staging.roadreadywheels.com/checkout/delivery');
//   await page.getByRole('button', { name: 'Continue' }).nth(1).click();
//   await page.waitForTimeout(2000);
//   await page.getByText('Credit Card').click();
//   await page.getByPlaceholder('Card Number').click();
//   await page.getByPlaceholder('Card Number').fill('4111 1111 1111 1111');
//   await page.getByPlaceholder('Card Number').press('Tab');
//   await page.getByPlaceholder('Security Code').fill('123');
//   await page.getByPlaceholder('Security Code').press('Tab');
//   await page.locator('#expiry_month').selectOption('2');
//   await page.locator('#expiry_year').selectOption('2035');
//   await page.click("[id='test-place-your-order']"); 
// await expect(page.locator('#order_summary')).toContainText('Credit Card');
// await expect(page.locator('#order_summary')).toContainText('$0.00');
// });