import { test, expect } from '@playwright/test';

test('payment_option', async ({ page }) => {
  test.slow();
  await page.goto('https://staging.roadreadywheels.com/');
  await page.getByPlaceholder('Enter password').click();
  await page.getByPlaceholder('Enter password').fill('roadready');
  await page.getByPlaceholder('Enter password').press('Enter');
  await page.getByRole('button', { name: 'SUBMIT', exact: true }).click();
  await page.locator('#make-button').getByText('-Select Make-').click();
  await page.getByRole('option', { name: 'BMW' }).click();
  await page.locator('#model-button').getByText('-Select Model-').click();
  await page.getByRole('option', { name: '320i' }).click();
  await page.getByRole('button', { name: 'SEARCH' }).click();
  await page.getByText('5', { exact: true }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Best Match 2001-2005 16x7 BMW' }).first().click();
  await page.getByRole('button', { name: ' Add To Cart' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: ' Complete Checkout' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.waitForTimeout(2000);
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('rg@g.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByRole('textbox', { name: 'First Name' }).fill('rishabh');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('gangwar');
  await page.getByRole('textbox', { name: 'Street Address 1' }).click();
  await page.getByRole('textbox', { name: 'Street Address 1' }).fill('dwarka');
  await page.getByRole('textbox', { name: 'Street Address 1' }).press('Tab');
  await page.getByRole('textbox', { name: 'Street Address 2' }).fill('delhi');
  await page.getByRole('textbox', { name: 'Street Address 2' }).press('Tab');
  await page.getByRole('textbox', { name: 'City' }).fill('delhi');
  await page.getByRole('textbox', { name: 'City' }).press('Tab');
  await page.locator('#order_ship_address_attributes_state_id').selectOption('3529');
  await page.getByRole('textbox', { name: 'Zipcode' }).click();
  await page.getByRole('textbox', { name: 'Zipcode' }).fill('30012');
  await page.locator('#order_ship_address_attributes_state_id').selectOption('3535');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('999999999');

  await page.getByRole('button', { name: 'Continue' }).nth(1).click();
  await page.waitForTimeout(2000);
  await page.goto('https://staging.roadreadywheels.com/checkout/delivery');
  await page.getByRole('button', { name: 'Continue' }).nth(1).click();
  await page.waitForTimeout(2000);
  await page.getByText('Credit Card').click();
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').fill('4111 1111 1111 1111');
  await page.getByPlaceholder('Card Number').press('Tab');
  await page.getByPlaceholder('Security Code').fill('123');
  await page.getByPlaceholder('Security Code').press('Tab');
  await page.locator('#expiry_month').selectOption('2');
  await page.locator('#expiry_year').selectOption('2035');
  await page.click("[id='test-place-your-order']"); 
await expect(page.locator('#order_summary')).toContainText('Credit Card');
await expect(page.locator('#order_summary')).toContainText('$0.00');
});